### ISSUE TITLE
single catalog class?

### ISSUE THREAD

**Issue by wsavran** [SCECcode/csep2#15]
Right now we have different classes to represent different types of catalogs. Should we simplify this and provide a single class with different functions to load the single catalog?

**Comment by khawajasim** [comment]
I would support your opinion about having a single class with different functions.

**Comment by thbeutin** [comment]
IMHO this make sense. We should check carefully, if we can implement a single type of data container, and import-/export filter methods on this container to fulfill the requirements of the various catalog classes.
Let's discuss this the next meeting after seeing project leader's comments here.

**Comment by wsavran** [comment]
im working on a solution that merges all similar catalogs into single class and still allows for subclassing if desired. will close when pr is merged

**Comment by wsavran** [comment]
closed with PR #31
