### ISSUE TITLE
Use PyCSEP for plotting test results without using EvaluationResult object 

### ISSUE THREAD

**Issue by khawajasim** [SCECcode/csep2#24]
If I use basic testing functions for evaluation, it would be difficult to use PyCSEP for making plots, as it uses EvaluationResult type input. It would be a good idea if plotting functions have the felxibility to plot results in raw form.

**Comment by wsavran** [comment]
i agree, but how would you consider the raw form of the results?

**Comment by khawajasim** [comment]
I mean to say like simple statistics, such as for likelihood based tests, it is quantile, and distribution. I must admit that it would be a bit messy to be able to handle plot for every type of test separately.

**Comment by wsavran** [comment]
true, i will think about how to best solve this issue. in general, you are right that we'd need a specific plotting type for each test separately. 

there might be a better way to plot them that currently exists that solves the problem. if you have any ideas let me know!

**Comment by khawajasim** [comment]
I shall be working on my problem in next days. If anything useful comes up, I would share. Thanks

**Comment by wsavran** [comment]
evaluation results now have a .plot() method that can be called on them. this doesn't address this issue in particular, but im closing for now. if this is still an issue with this new feature we can reopen.
