### ISSUE TITLE
Dependency problem (mpl_toolkits.basemap)

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/csep2#27]
The module mpl_toolkits.basemap is not found, at least with the matplotlib version specified in the requirements file. Apparently this is a problem with pip3 (reproduced both from pycharm and using the instructions of csep2). It appears that it is only found in conda repository. Could we reconsider on choosing another library for basemaps plotting?

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pciturri/Desktop/Forecasting/csep2_test/csep2/csep/__init__.py", line 1, in <module>
    from csep.core import forecasts
  File "/home/pciturri/Desktop/Forecasting/csep2_test/csep2/csep/core/forecasts.py", line 13, in <module>
    from csep.utils.plots import plot_spatial_dataset
  File "/home/pciturri/Desktop/Forecasting/csep2_test/csep2/csep/utils/plots.py", line 5, in <module>
    from mpl_toolkits.basemap import Basemap
ModuleNotFoundError: No module named 'mpl_toolkits.basemap`

**Comment by wsavran** [comment]
true, it looks like there is an explicit line for the basemap module in the requirements.yml that conda uses to install the dependencies. this module is only used by one function in the plotting module, so i think we can actually remove this dependency.

**Comment by wsavran** [comment]
solved by #30

**Comment by wsavran** [comment]
reopening until cartopy is updated to 0.18 in the requirements.

**Comment by khawajasim** [comment]
I encountered the same problem. I looked for a solution online. It was solved by adding a line manually in the code and copying a file at certain location. 

import os #(This line and line below are for mpl_toolkit.basemap) So always run it for basemap.
os.environ['PROJ_LIB'] = 'C:/Users/Khawajasim/Anaconda3/Lib/site-packages/mpl_toolkits/basemap'

**Comment by wsavran** [comment]
are you using the most up-to-date code in the repository? i removed the dependency for the Basemap module, so im wondering if that is the reason this error is still showing up.

**Comment by khawajasim** [comment]
No sorry I was using 2,3 months old repository. Just updated it. I see a lot has changed since then.
